---
- name: Copy course notebooks to user's scratch directories
  block:
    - name: Copy and unzip course materials
      ansible.builtin.unarchive:
        src: workshop_materials.zip
        dest: /scratch
