name: geospatial
channels:
  - conda-forge
dependencies:
  # Python
  - python=3.10
  # Jupyter Lab
  - jupyterlab>=3.1.0
  # Python scientific libraries
  - numpy>=1.20.0
  - numba>=0.53
  - matplotlib>=3.4.0
  - xarray>=0.17
  # Geospatial libraries
  - rasterio>=1.2.0
  - geopandas>=0.8.0
  - rioxarray>=0.7.0
  - earthpy>=0.9.4
