on:
  pull_request_target:
    branches: main
      - 'main'
    paths:
      - 'workshop_materials/**'
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
        fetch-depth: 0
    - name: Zip Course materials 
      run: |
        rm playbooks/roles/transfer_workshop_materials/files/workshop_materials.zip
        zip -r playbooks/roles/transfer_workshop_materials/files/workshop_materials.zip workshop_materials
    - uses: actions/upload-artifact@v3
      with:
        name: workshop_materials
        path: playbooks/roles/transfer_workshop_materials/files/workshop_materials.zip
    - name: Commit files
      run: |
        git config --local user.email "github@uu.nl"
        git config --local user.name "GitHub Utrecht University"
        git commit -a -m "Update course materials"
      continue-on-error: true
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
      continue-on-error: true
